---
title: "Effect of urbanization and varying diets on the microbiome of the western black widow (*Latrodectus hesperus*)"
output: 
  word_document:
    reference_docx: bwm-styles.docx
bibliography: bwm-references.bib
csl: oikos.csl
---

# Abstract {.unnumbered}

Keywords :


\newpage
# Introduction {.unnumbered}

Human-induced environmental modifications alter trophic interactions by reshaping prey and predator communities (van der Putten, et al. 2004; Dorresteijn, et al.2015). An increasing number of studies report a massive loss of arthropod species diversity, which is the most diverse group in the animal kingdom (Giribet and Edgecombe 2010; Lebuhin et al. 2013), due to the combined effects of urbanization and human activities (Newbold et al. 2015, Bosmans et al. 2018, Seibold et al. 2019). For instance, urbanization transforms the habitat characteristics where predatory arthropods hunt (REFS), which may then incur changes in the community composition of their prey (Hallmann et al. 2017, Seibold et al. 2019). Consequently, these new environmental pressures can lead to drastic diet changes which may impair the capacity of predatory arthropods to survive (s’adapter) in urbanized habitats (Weisser, and Siemann, 2008 ; Yang, and Gratton, 2014).
Numerous studies have shown that varying diets can influence the physiology, behaviour, and fitness of wild predatory animals (Toft,1999; Acevedo-Whitehouse et Duffus, 2009; Hancorresponding and Dingemanse, 2015). Changes in species composition can alter the quantity of available prey for predatory arthropods, food abundance, but also their quality, nutrient composition, for example, via reduced nutritional components (Kim et al. 2017). The microbial communities inhabiting arthropods’ bodies provide numerous functions related to food consumption such as nutrient acquisition, food digestion, and food detoxification (Brune and Ohkuma 2011, LeBlanc et al. 2013, Boone et al. 2013). The microbiome of arthropods may thus play a key role for their survival and reproduction in a changing landscape. Recently, the role of diet has been highlighted as a critical factor mediating the structure of arthropod microbiome communities (Kennedy et al. 2020). Yet, we still have very limited knowledge on the ecological mechanisms driving arthropod microbiome diversity in the wild, such as habitat change and prey diet. Moreover, studies of microbiome diversity in arthropods have been mostly descriptive, and the ecological and evolutionary consequences of host-microbe interactions for arthropods are just beginning to be explored (Engel and Moran 2013, Parks et al. 2017). Accordingly, the composition of the microbial environment of arthropods could indicate adaptive responses to changes in habitat and prey diversity.
In this study, we used the western black widow (Latrodectus hesperus), a sedentary predatory spider that uses its web as a hunting tool, to test the effect of urbanization and prey diet on their micriobiota composition. This predator can stay in one place for almost a year and feeds exclusively on local prey (Salomon,2011; Schraft, H., et al. 2021). While the western black widow is a facultative generalist, it has been shown to benefit from a diversity of prey to fulfill its nutritional requirements (Salomon, 2011). A balanced diet of multiple prey types may be adaptive for spiders because polyphagy provides access to a variety of nutrients not available from a single prey source. This has been shown to maximize growth rate and survival of juveniles (Uetz et al. 1992, Toft 1999). However, a mixed diet may be limited by the availability of certain prey types in the habitat where black widows establish themselves. Western black widows can be found both in desertic and urban environments. They are therefore ideal study systems to quantify the consequences of urbanization via the study of their microbiota. They could potentially serve as bioindicators informing on the state of the surrounding ecological communities (Gregorič et al. 2022, Hose et al. 2002, De et al. 2022).
Here, we combined field and laboratory experiments to evaluate the impacts of urbanization on microbiome communities and body condition of western black widows. In the field, we compared spiders collected from 4 different sites to measure the impacts of urbanization on microbiome diversity. Our objective is to characterize and compare the gut and web bacterial communities of western black widows according to their environment: desert (natural) versus urban. We hypothesize that the diversity and structure of the bacterial communities of the gut and webs will differ between spiders collected in desertic and urban habitats. Because prey diversity would likely be lower in urban environments (Bosmans et al. 2018), we predict that gut and web bacterial diversity will be higher for spiders collected in the desert. In a subsequent laboratory experiment, we studied the influence of a restricted diet on microbiome diversity. Our objective is to evaluate the effect of a restricted diet (i.e. crickets vs isopods) on the alpha and beta diversity of the western black widow’s gut microbiome. First, knowing there is a functional relationship between diet and gut microbiome, spiders that consumed a similar diet should have a homogeneous community. Second, the rate of variation in beta diversity should be explained by the spider’s diet. A diet composed of crickets should ellicit a greater abundance and diversity since crickets are omnivores with a high protein and fruit/vegetable diet (Ng et al. 2018). On the contrary, spiders restricted with an isopod diet should have a lower variety of microorganisms specific to the carrot-based diet that was provided to the isopods. The composition of the bacterial microbiota is influenced by the interactions of the host microbiota through their food web. The main drivers of variation in bacterial microbiota within each trophic level differed according to spatial scales, their diet and whether or not they shared the same local environment, so diet can affect their microbiota through its nutritional or chemical composition, but also through the ingestion of the bacteria it contains (Muegge, et al. 2011, Dion-Phénix et al. 2021)

The last objective would be to identify if there is a basal microbiome in the L. Herperus species. One of the hypothesis would be that The permanent core microbiome of the species-specific microbial flora and thus be observed across groups leading to a stable and predictable microbial community. Evidence for this eco-evolutionary model of microbial community assembly within these widow spider host species and their respective tissues (Brooks, et al.2016; Dunaj et al. 2020). This should thus be resistant to the influence of diet on the community (Chu, Spencer, Curzi, Zavala, & Seufferheld, 2013 ; Engel & Moran, 2013 ; Reese & Dunn, 2018 ; Ruokolainen , Ikonen, Makkonen, & Hanski, 2016 ; Russell et al., 2009 ; Sanders et al., 2014 ). These results could contribute to a better understanding of how host-microbe interactions and microbial communities may play in the evolution and adaptation of their hosts.

Sedentary spiders that build a capture web have enormous potential for diversity and ecological abundance on it (Coddington & Colwell, 2000). The web is an extension of their sensory and chemical organs. It allows it to communicate and store information from its environment to its host. The web would therefore be an excellent way to characterize the spider's local habitat (Keiser et al. 2018) and a relevant tool as a bioindicator of environments by its microbiota. Deux études pionnière menée en laboratoire ont démontré que les toiles d'araignées veuves contiennent des traces génétiques de l'hôte et de sa proie unique (Xu et al., 2015 ; Blake et al., 2016). The data collected would help identify the type of interaction (prey, predators) taking place in the spider's local environment as well as information on ecosystem health. Spider webs are powerful biofilters of environmental DNA (Gregorič, et al. 2022). Their recent results show that genetic remains on webs allow the detection of target organisms and also demonstrate that DNA from spider webs is useful in the search for community compositions.



\newpage
# Materials and methods {.unnumbered}

## Study system : The western black widow spider (*Latrodectus hesperus*)
Western black widows (Latrodectus hesperus) will be used as a biological model to assess the impact of diets on the structure of their gut microbiome. L. hesperus occurs in cities and desert habitats from Mexico to western Canada. It is a polyphagous predatory species that feeds on a wide variety of prey. 
They are considered generalist predators. Mature females are mostly solitary and sedentary. Indeed, it is a predatory arthropod that has a predation strategy based on the creation of a 3D web that is defined by a sit and wait mode. They would tend to stay on their web for a long time and feed locally on the prey that falls on their web (Dunaj, Bettencourt, Garb, et al. ,2020). The web would also be an interesting bio indicator that could inform on the nature of prey, predators and bacteria. Indeed, the web is a rich microbial environment that could provide information about the ecosystem and available prey.

Predatory arthropods have a relatively simple gut and the diversity of their microbiome seems more likely to be affected by their diet. Black widow spiders (genus Latrodectus) are therefore a particularly suitable system to understand how microbes influence spider evolution The black widows used in the experiment come from a wild population collected and were reared and maintained in the laboratory under standardized conditions for a minimum of 3 years. The individuals were isolated and exposed to the same conditions of temperature (24°C ± 2°C), humidity (40% RH) and a day-night cycle of 12h-12h. Non-experimental individuals were fed twice a month with a live cricket.

## Methods for the microbiome of spiders in the field

With L. hesperus specimens reared in the laboratory at the Université du Québec à Montréal (UQAM), several compartments (cuticles, bristles, feces, etc.) were tested with different protocols from QIAGEN and targeting different genetic materials (eithergenetic material (either DNA or bacterial RNA). It was finally determined that bacterial DNA would be extracted more efficiently with the DNeasy® PowerSoil® protocol (QIAGEN).

### Data collection

*we need to describe the field conditions, temperature, precipitation, land cover, blablabla*

During the sampling period (spring 2020), a total of 14 specimens of L. Hesperus were captured in the vicinity of and outside the city of Tucson, Arizona (USA). These specimens were distributed among 4 different sites, including 2 desert wilderness sites (Chaos Canyon (CC) and Dove Mountain (DM)) and 2 urban sites (University of Arizona Campus (UA) and a Lowe's (LO) parking lot). Spider webbing was collected for each individual captured under relatively sterile individual captured under relatively sterile conditions (latex gloves and alcohol) with a Falcon tube and a disinfected metal rod. The webs were recovered by turning the rod in the center of the specimen and was captured with a Falcon tube and a metal rod. The 14 individuals and their respective webs were identified and transported alive to storage at -20°C. The samples were finally sent by mail (placed in dry ice) to the laboratories of UQAM. The samples were placed on ice at irregular intervals during initial storage, transportation and finally final storage at the UQAM laboratories. The samples of each location and type, however, underwent this intermittent cooling uniformly. 

## Methods for the microbiome of spiders in the laboratory experiment

### Feeding bioassay

In a laboratory feeding experiment, we tested whether a single meal has the potential to alter the gut bacterial community of black widow.
The spiders were randomly allocated to three treatments: (1) no food (control), (2) a meal consisting of Gryllodes sigillatus (crickets), and (3) a meal consisting of Porcellionides pruinosus (isopod). Isopods are present in city. Isopods are poor in nutrients and contain little protein.
Crickets represents one of the common preys of spider in labotary. They represent a food rich in lipid and protein that is beneficial to spiders
Each individual was first transferred to a cardboard support where they build their web for 5 days. Second, the black widows were divided into their three distinct groups and identified in the database. Then, prey was administered weekly to maintain them at their satiation level. The diets were maintained for 6 weeks and the spiders were dissected 72 hours after their last meal. In the control group, the spiders were not fed for 6 weeks. 

### Cricket and isopod

The crickets and isopods used are within the range of potential natural prey. They both come from a controlled and ethical farm located on the south shore of Montreal.
For the first diet, crickets of the species Gryllodes sigillatus were chosen and raised in the laboratory. They are housed in ventilated containers and maintained at room temperature. They are fed regularly with an assortment of vegetables, pet food and plants. Crickets are a good source of protein while being low in fat. They also have a very low calcium/phosphorus ratio. For the second diet, isopods of the species Porcellionides pruinosus were chosen and raised in the laboratory. The sowbugs are small terrestrial crustaceans that are not very nutritious. They are very low in fat and protein but very rich in several minerals, including calcium. They are kept in their container in a humid culture environment and at room temperature. They are fed with carrots and vegetables about twice a week.

## Sample processing for the field and laboratory experiment

The analysis of intestinal bacteria was performed on dissected digestive tracts and the lipid profile. Each spider was transferred to a plastic jar with a lid to be anesthetized by introducing CO2 for 2 to 5 minutes than by freezing in a -20°C freezer. The samples were then rinsed in three steps. I performed an initial rinse with sterile pure water for 1 minute, followed by a second rinse with 70% ethanol for 5 minutes, and then a series of three more rinses times with sterile pure water. The hindgut of each individual was dissected in 0.1 M Sodium Chloride, 0.015 M Sodium Citrate, 0.1% Diethyl Pyrocarbonate sterile solution with sterile forceps under a binocular loupe, placed in 1.5 ml microcentrifuge tubes, washed three times with sterile water. All manipulations were performed under flame and the equipment sterilized at each use. Spiders being sacrificed, then stored at -20°C until DNA was extracted. the dissection was done in the same day of their euthanasia.

An external sterilization of the cuticle was performed before the bacterial DNA extractions for each spider to avoid any contamination to the internal microbiota. The specimens were first placed in a Falcon tube containing ultrapure water and then subjected to the sonicator  for 60 sec. They were then immersed in 95% ethanol and vortexed 30 sec. The same  step follows with 75% ethanol. Afterwards, the spiders are placed in a sterile mortar, then crushed to extract the inner liquids with a filter pipette and added to the   solution C1 of the DNeasy® PowerSoil® kit (QIAGEN), which will be used for all DNA extractions. 

It is therefore the complete internal environment (fatty masses, cephalothorax, intestinal tract, ovaries, legs, etc. except for the cuticles) which is evaluated for its microbiota of spider on the field. The respective webs were first dissected and cut under the hood or Bunsen flame with knives with sterile knives and tweezers and then incorporated into solution C1 of the DNeasy® PowerSoil® kit (QIAGEN) in order to analyze their to analyze their surfaces for bacteria. For spider diet, after 6 weeks of a strict diet, three individuals per group were sacrificed in order to collect the digestive tract and the lipidic profile to extract the microbial DNA. The dissections were performed 72h after their last meal. Each spider was sterilized and then dissected under a binocular light microscope before used the DNeasy® PowerSoil® kit (QIAGEN). A PCR was performed with the bacterial DNA extracted with the PCR Master Mix (QIAGEN) as well as the buffer and amplifying solution from Invitrogen company.

À VALIDER
Bactérie Tm = 57°C Eucaryotes Tm = 61°C
Bacteria with 5uL DNA and Eucaryote 2uL DNA
Polymerase : Phusion Hot Start II High-Fidelity


## Data preparation and statistical analyses


\newpage
# Results {.unnumbered}


\newpage
# Discussion {.unnumbered}

*Our study provides a better understanding of the impacts of urbanization on the microbial ecology of L. hesperus in Arizona. It will also help determine how prey encountered by black widows shape the structure of their microbiome.*


\newpage
# References {.unnumbered}

<div id="refs"></div>
